CREATE TABLE `cases_common` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `bank_id` SMALLINT(5) UNSIGNED DEFAULT NULL,
  `product_category` char(2) DEFAULT NULL,
  `penztar` varchar(255) DEFAULT NULL,
  `szerzodes_szam` varchar(255) DEFAULT NULL,
  `szerzodeses_osszeg_emeles` TINYINT(1) UNSIGNED DEFAULT NULL,
  `ugyfelelegedettsegi_lap_sorszama` varchar(255) DEFAULT NULL,
  `ugyfelelegedettsegi_lap_beerkezese` date DEFAULT NULL,
  `igenyfelmero_adatlap_sorszama` varchar(255) DEFAULT NULL,
  `igenyfelmero_adatlap_beerkezese` date DEFAULT NULL,
  `szerzodeskotes_datuma` date DEFAULT NULL,
  `varhato_indulas_datuma` date DEFAULT NULL,
  `befizetes_allapota` varchar(255) DEFAULT NULL,
  `termekcsalad` varchar(255) DEFAULT NULL,
  `futamido_ev` tinyint(2) UNSIGNED DEFAULT NULL,
  `futamido_ho` tinyint(3) UNSIGNED DEFAULT NULL,
  `befizetes_modja` varchar(255) DEFAULT NULL,
  `szamlanyitasi_dij` int(11) UNSIGNED DEFAULT NULL,
  `szamlanyitasi_dij_kedvezmeny` varchar(255) DEFAULT NULL,
  `havi_befizetes` int(11) UNSIGNED DEFAULT NULL,
  `szamlavezetesi_dij` varchar(255) DEFAULT NULL,
  `ltp_szerzodes_osszege` varchar(255) DEFAULT NULL,
  `megjegyzes` text CHARACTER SET utf8 COLLATE utf8_hungarian_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `cases_common` ADD INDEX (`user_id`);

CREATE TABLE `cases_client_data` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `case_id` int(11) UNSIGNED DEFAULT NULL,
  `ugyfel_forras` VARCHAR(5) DEFAULT NULL,
  `ugyfel_tipusa` CHAR(2) DEFAULT NULL,
  `nev` varchar(255) DEFAULT NULL,
  `ceg_kepviselojenek_neve` varchar(255) DEFAULT NULL,
  `szuletesi_nev` varchar(255) DEFAULT NULL,
  `anyja_szuletesi_neve` varchar(255) DEFAULT NULL,
  `szuletesi_hely` varchar(255) DEFAULT NULL,
  `szuletesi_ido` date DEFAULT NULL,
  `adoszam` varchar(10) DEFAULT NULL,
  `azonosito_okmany_tipusa` char(2) DEFAULT NULL,
  `azonosito_okmany_szama` varchar(255) DEFAULT NULL,
  `allampolgarsag` varchar(255) DEFAULT NULL,
  `iranyitoszam` int(11) DEFAULT NULL,
  `varos` varchar(255) DEFAULT NULL,
  `utca_hazszam` varchar(255) DEFAULT NULL,
  `levelezesi_cim` varchar(255) DEFAULT NULL,
  `telefonszam` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `epulet_cime` varchar(255) DEFAULT NULL,
  `lakasok_szama` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cases_beneficiary` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `case_id` int(11) UNSIGNED DEFAULT NULL,
  `van_kedvezmenyezett` TINYINT(1) UNSIGNED DEFAULT NULL,
  `nev` varchar(255) DEFAULT NULL,
  `szuletesi_nev` varchar(255) DEFAULT NULL,
  `anyja_szuletesi_neve` varchar(255) DEFAULT NULL,
  `szuletesi_hely` varchar(255) DEFAULT NULL,
  `szuletesi_ido` date DEFAULT NULL,
  `adoazonosito_jel` varchar(10) DEFAULT NULL,
  `allampolgarsag` varchar(255) DEFAULT NULL,
  `iranyitoszam` int(11) DEFAULT NULL,
  `varos` varchar(255) DEFAULT NULL,
  `utca_hazszam` varchar(255) DEFAULT NULL,
  `levelezesi_cim` varchar(255) DEFAULT NULL,
  `telefonszam` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
